<a href="https://colab.research.google.com/github/onleey/numpy_demo/blob/master/200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.


공식문서 https://numpy.org/doc/stable/  
numpy 100 문제 https://github.com/rougier/numpy-100

# 1. 데이터 생성

In [1]:
import numpy as np

np.zeros( ) 생성할 개수 삽입 . zero라 0이 값.

In [7]:
a = np.zeros(3) #1차원 배열 생성 (벡터)
a

array([0., 0., 0.])

In [9]:
print(a)

[0. 0. 0.]


In [11]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [15]:
print(a.__repr__)
print(a.__str__)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7e47b9047690>
<method-wrapper '__str__' of numpy.ndarray object at 0x7e47b9047690>


In [17]:
print(type(a))

<class 'numpy.ndarray'>


np.array()



In [19]:
a = np.array([1,2,3])   # 1차원 배열 =벡터
a

array([1, 2, 3])

In [23]:
print(a)
print(type(a))
print(dir(a))

[1 2 3]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [26]:
#2차원 배열 = 행렬
b = np.array([[1,2],[3,4]])   #2행 2열
b

array([[1, 2],
       [3, 4]])

In [33]:
print(b)
print(type(b))
print(dir(b))
print(b.shape)   #.shape 현재 몇행 몇렬인지 알고싶다.

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__

In [37]:
# 3차월 배열 , 그이상은 텐서(tensor)라고 함
c = np. array([[[1,2],[3,4]],[[5,6],[7,8]]])  #2층(면,공간), 2행, 2열
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
print(c)
print(type(c))
print(dir(c))
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__po

In [43]:
a = np.array ([1,2,3])
print(a)
print(a[0])

[1 2 3]
1


In [45]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 출력된다.
# numpy는homogenous이다. 즉, 같은 타입만 저장 할 수 있다.
a = np.array ([1,'2',3])
print(a)
print(a[0])

['1' '2' '3']
1


In [48]:
#논리값에서 False는 0, True는 1로 저장함
a = np.array ([0,False,1,True])
print(a)
print(a[0])

[0 0 1 1]
0



#np.zeros
```
-tuple로 인자를 넣으면 그대로 모양을 만든다.   
- (2,3): 2행 3열의 행렬을 만든다.   
- zeros는 기본값으로 0.으로 값을 모두 채운다.
  -np.zeros((2,3))
  -np.zeros([2,3])

```

In [54]:
a = np.zeros(3)

print(a)
print(a.shape)

[0. 0. 0.]
(3,)


In [56]:
a = np.zeros((2,3))

print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [57]:
a = np.zeros([2,3])

print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


### np.eye
- eye는 단위행렬
- 숫자만 사용할 수 있다.


In [62]:
a= np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
# eye는 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬생성
a = np.eye(3,2) #3행 2열
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [72]:
# 1이 시작되는 위치를 지정할 수 있다. (k=1)
a= np.eye(3,4,k=1) #3행 4열
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 단위행렬 identity
- 수학에서 단위행렬은 영어로 identity matrix
- 크기 한 개만 지정해서 생성할 수 있다.

In [78]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.full
 - 지정한 크기의 배열을 생성하고 채울값을 지정 한다.

In [83]:
#2행 2열의 행렬을 생성하고 1로 초기화 해준다.
a = np.full((3,4),1) #np.full(shape. fill_value)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [89]:
#2행 2열의 행렬을 생성하고 각 행마다 1, 2로 초기화 해준다.
a= np.full((2,2),[1,2])
a

array([[1, 2],
       [1, 2]])

In [90]:
# 2행 2열의 행렬을 생성하고 각각 1,2,3,4,로 초기화 해준다.
a= np.full((2,2),[[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.  

In [5]:
a = np.empty(3)
a

array([0. , 0.5, 1. ])

In [8]:
# 2행2열이 생성됨
a= np.empty((2,3))
a

array([[4.90509540e-310, 0.00000000e+000, 2.05833592e-312],
       [6.79038654e-313, 2.14321575e-312, 2.27053550e-312]])

### np.ones
 - 배열의 모든 값을 1로 채운다.


In [10]:
a = np.ones(3)
a

array([1., 1., 1.])

In [14]:
a = np.ones((2,3))
a


array([[1., 1., 1.],
       [1., 1., 1.]])

### _like
- _like가 붙으면 shape가 같게 만들어 진다.
- 연산하기 위해서 shape를 맞춰야 하는 경우가 있다.


In [16]:
# 2행 3열의 배열 생성

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b = np.ones_like(a) # a배열의 shape를 복사한다.
b

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
c = a+b
c

array([[2, 3, 4],
       [5, 6, 7]])

### linespace
- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세번째 num 인자 값이 생략되어 있으므로 start와
  end 계산해서 default 50이 생성된다.
- linspace(start, end, num)
- linspace (0,49) # 50 #num의 default value 50



In [26]:
a = np.linspace(0,49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [30]:
#endpoint를 False로 설정을 하면 5가 포함이 안된다.
a = np.linspace(0, 5, endpoint=False)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

## logspace
-linspace와 비슷하다.   
-log scale을 사용하는 차이가 있다.   

In [37]:
np.logspace(1,50,30) #1부터 50까지 사이의 30개의 요소를 생성한다.

array([1.00000000e+01, 4.89390092e+02, 2.39502662e+04, 1.17210230e+06,
       5.73615251e+07, 2.80721620e+09, 1.37382380e+11, 6.72335754e+12,
       3.29034456e+14, 1.61026203e+16, 7.88046282e+17, 3.85662042e+19,
       1.88739182e+21, 9.23670857e+22, 4.52035366e+24, 2.21221629e+26,
       1.08263673e+28, 5.29831691e+29, 2.59294380e+31, 1.26896100e+33,
       6.21016942e+34, 3.03919538e+36, 1.48735211e+38, 7.27895384e+39,
       3.56224789e+41, 1.74332882e+43, 8.53167852e+44, 4.17531894e+46,
       2.04335972e+48, 1.00000000e+50])

##데이터타입

In [39]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [40]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [43]:
b = np.array([1,2,3], dtype=np.int8) # -128~ +127까지만 허용이 된다.
b

array([1, 2, 3], dtype=int8)

In [44]:
b = np.array([-128,-127,5,100,127], dtype=np.int8)
b

array([-128, -127,    5,  100,  127], dtype=int8)

In [45]:
#np.int8은 -128~127 사이의 값을 저장할 수 있다.
b = np.array([-128,-127,5,100,128], dtype=np.int8)
b

array([-128, -127,    5,  100, -128], dtype=int8)