<a href="https://colab.research.google.com/github/onleey/numpy_demo/blob/master/200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.


공식문서 https://numpy.org/doc/stable/  
numpy 100 문제 https://github.com/rougier/numpy-100

# 1. 데이터 생성

In [8]:
import numpy as np

np.zeros( ) 생성할 개수 삽입 . zero라 0이 값.

In [7]:
a = np.zeros(3) #1차원 배열 생성 (벡터)
a

array([0., 0., 0.])

In [9]:
print(a)

[0. 0. 0.]


In [11]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [15]:
print(a.__repr__)
print(a.__str__)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7e47b9047690>
<method-wrapper '__str__' of numpy.ndarray object at 0x7e47b9047690>


In [17]:
print(type(a))

<class 'numpy.ndarray'>


np.array()



In [19]:
a = np.array([1,2,3])   # 1차원 배열 =벡터
a

array([1, 2, 3])

In [23]:
print(a)
print(type(a))
print(dir(a))

[1 2 3]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [26]:
#2차원 배열 = 행렬
b = np.array([[1,2],[3,4]])   #2행 2열
b

array([[1, 2],
       [3, 4]])

In [33]:
print(b)
print(type(b))
print(dir(b))
print(b.shape)   #.shape 현재 몇행 몇렬인지 알고싶다.

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__

In [37]:
# 3차월 배열 , 그이상은 텐서(tensor)라고 함
c = np. array([[[1,2],[3,4]],[[5,6],[7,8]]])  #2층(면,공간), 2행, 2열
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
print(c)
print(type(c))
print(dir(c))
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__po

In [43]:
a = np.array ([1,2,3])
print(a)
print(a[0])

[1 2 3]
1


In [45]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 출력된다.
# numpy는homogenous이다. 즉, 같은 타입만 저장 할 수 있다.
a = np.array ([1,'2',3])
print(a)
print(a[0])

['1' '2' '3']
1


In [48]:
#논리값에서 False는 0, True는 1로 저장함
a = np.array ([0,False,1,True])
print(a)
print(a[0])

[0 0 1 1]
0



#np.zeros
```
-tuple로 인자를 넣으면 그대로 모양을 만든다.   
- (2,3): 2행 3열의 행렬을 만든다.   
- zeros는 기본값으로 0.으로 값을 모두 채운다.
  -np.zeros((2,3))
  -np.zeros([2,3])

```

In [54]:
a = np.zeros(3)

print(a)
print(a.shape)

[0. 0. 0.]
(3,)


In [56]:
a = np.zeros((2,3))

print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [57]:
a = np.zeros([2,3])

print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


### np.eye
- eye는 단위행렬
- 숫자만 사용할 수 있다.


In [62]:
a= np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
# eye는 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬생성
a = np.eye(3,2) #3행 2열
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [72]:
# 1이 시작되는 위치를 지정할 수 있다. (k=1)
a= np.eye(3,4,k=1) #3행 4열
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 단위행렬 identity
- 수학에서 단위행렬은 영어로 identity matrix
- 크기 한 개만 지정해서 생성할 수 있다.

In [78]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.full
 - 지정한 크기의 배열을 생성하고 채울값을 지정 한다.

In [83]:
#2행 2열의 행렬을 생성하고 1로 초기화 해준다.
a = np.full((3,4),1) #np.full(shape. fill_value)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [89]:
#2행 2열의 행렬을 생성하고 각 행마다 1, 2로 초기화 해준다.
a= np.full((2,2),[1,2])
a

array([[1, 2],
       [1, 2]])

In [90]:
# 2행 2열의 행렬을 생성하고 각각 1,2,3,4,로 초기화 해준다.
a= np.full((2,2),[[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.  

In [5]:
a = np.empty(3)
a

array([0. , 0.5, 1. ])

In [8]:
# 2행2열이 생성됨
a= np.empty((2,3))
a

array([[4.90509540e-310, 0.00000000e+000, 2.05833592e-312],
       [6.79038654e-313, 2.14321575e-312, 2.27053550e-312]])

### np.ones
 - 배열의 모든 값을 1로 채운다.


In [10]:
a = np.ones(3)
a

array([1., 1., 1.])

In [14]:
a = np.ones((2,3))
a


array([[1., 1., 1.],
       [1., 1., 1.]])

### _like
- _like가 붙으면 shape가 같게 만들어 진다.
- 연산하기 위해서 shape를 맞춰야 하는 경우가 있다.


In [16]:
# 2행 3열의 배열 생성

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b = np.ones_like(a) # a배열의 shape를 복사한다.
b

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
c = a+b
c

array([[2, 3, 4],
       [5, 6, 7]])

### linespace
- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세번째 num 인자 값이 생략되어 있으므로 start와
  end 계산해서 default 50이 생성된다.
- linspace(start, end, num)
- linspace (0,49) # 50 #num의 default value 50



In [26]:
a = np.linspace(0,49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [30]:
#endpoint를 False로 설정을 하면 5가 포함이 안된다.
a = np.linspace(0, 5, endpoint=False)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

## logspace
-linspace와 비슷하다.   
-log scale을 사용하는 차이가 있다.   

In [37]:
np.logspace(1,50,30) #1부터 50까지 사이의 30개의 요소를 생성한다.

array([1.00000000e+01, 4.89390092e+02, 2.39502662e+04, 1.17210230e+06,
       5.73615251e+07, 2.80721620e+09, 1.37382380e+11, 6.72335754e+12,
       3.29034456e+14, 1.61026203e+16, 7.88046282e+17, 3.85662042e+19,
       1.88739182e+21, 9.23670857e+22, 4.52035366e+24, 2.21221629e+26,
       1.08263673e+28, 5.29831691e+29, 2.59294380e+31, 1.26896100e+33,
       6.21016942e+34, 3.03919538e+36, 1.48735211e+38, 7.27895384e+39,
       3.56224789e+41, 1.74332882e+43, 8.53167852e+44, 4.17531894e+46,
       2.04335972e+48, 1.00000000e+50])

##데이터타입

In [39]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [40]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [43]:
b = np.array([1,2,3], dtype=np.int8) # -128~ +127까지만 허용이 된다.
b

array([1, 2, 3], dtype=int8)

In [44]:
b = np.array([-128,-127,5,100,127], dtype=np.int8)
b

array([-128, -127,    5,  100,  127], dtype=int8)

In [45]:
#np.int8은 -128~127 사이의 값을 저장할 수 있다.
b = np.array([-128,-127,5,100,128], dtype=np.int8)
b

array([-128, -127,    5,  100, -128], dtype=int8)

In [46]:
#np.int8은 -128~127 사이의 값을 저장할 수 있다.
#128이 -128로 저장된다. (쓰레기 값)
b = np.array([-128,-127,5,100,128], dtype=np.int8)
b

array([-128, -127,    5,  100, -128], dtype=int8)

In [48]:
#python의int를 지정한다.
c= np.array([127,2,3,-128],dtype=int)  #int는 python의 데이터타입이다.
c

array([ 127,    2,    3, -128])

In [51]:
print(c.dtype)            #python의 int == numpy의 64
print(type(c))

int64
<class 'numpy.ndarray'>


# python의 도움말

In [54]:
sum?

In [ ]:
help(sum)

#numpy 도움말

In [56]:
# np.lookfor('sum')

In [59]:
a = np.array([[1,2,3],[4,5,6]])
# array의 shape를 알려준다.
a.shape    #(2,3)은 2행 3열이라는 뜻

(2, 3)

In [61]:
# array이 몇차원인지 알려준다.
a.ndim # ndim 은 몇차원인지를 알려줌

2

In [64]:
a.dtype  # array배열의 타입을 알수있다.

dtype('int64')

In [66]:
a.size   #요소개수를 알려준다.
        #shape로도 알수있다.

6

In [70]:
# 요소당 byte수를 알려준다.
a.itemsize   #8bit = 1byte   / 64bit = 8 byte

8

## numpy 와 python의 속도차이

In [9]:
np.arange(10)  # ([start,] end, [step]) 1,3은 생략가능 range랑 동일

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#num을 이용한 계산
%time np.sum(np.arange(1000000000))

CPU times: user 1.43 s, sys: 1.84 s, total: 3.28 s
Wall time: 3.28 s


499999999500000000

In [11]:
#python을 이용한 계산
%time sum(range(1000000000))

CPU times: user 27.1 s, sys: 115 ms, total: 27.2 s
Wall time: 29.4 s


499999999500000000

같은 np.sum()을 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.


In [12]:
%time np.sum(np.arange(1000000000))

CPU times: user 2.17 s, sys: 6.21 s, total: 8.38 s
Wall time: 10.2 s


499999999500000000

In [13]:
%time np.sum(range(100000000))

CPU times: user 12.3 s, sys: 2.17 s, total: 14.5 s
Wall time: 14.5 s


4999999950000000

## copy

 ※ 대입문 6가지
 a = 1
 a = b = 1
 a,*b = 1,2,3 #튜플 할당
 a += 1
 global , nolocal

#python 에서 copy

In [14]:
a= [1,2,3] #list

In [15]:
b =a

In [16]:
b

[1, 2, 3]

In [21]:
a is b

True

In [22]:
# a와 b가 메모리 공유
# b값을 변경하면 a도 같이 변경된다
b[0] = 7

In [23]:
print(b)
print(a)

[7, 2, 3]
[7, 2, 3]


1차원일때 copy

In [24]:
 a = [1,2,3]


In [28]:
# copy()는 똑같은 값만 가지고 메모리는 공유하지 않는다. 즉 deep copy가 된다.
b = a.copy()

In [29]:
a is b

False

In [30]:
id(a)

138346781646976

In [32]:
id(b)

138346781647488

In [34]:
a == b  #값 비교


True

In [36]:
b[0]= 8

print(a)
print(b)

[1, 2, 3]
[8, 2, 3]


In [37]:
print(a is b)
print (a == b)

False
False


list가 2차원 일때 copy

In [57]:
a = [[1,2,3]]

In [40]:
type(a)

list

In [58]:
# shallow copy (얕은 카피 )
b=a.copy()

In [56]:
print (a is b)
print (a == b)

False
True


In [64]:
print(a[0])
print(b[0])

[10, 2, 3]
[10, 2, 3]


In [63]:
b[0][0] = 10

In [67]:
print(a[0])
print(b[0])

[10, 2, 3]
[10, 2, 3]


In [71]:
print(a[0] == b[0])
print(a[0] is b[0])

True
True


In [53]:
import copy

In [72]:
a = [[1,2,3]]
b = copy.deepcopy(a) # list가 2차원 일 때, deep copy를 하기 위해서 copy 모듈에 있는 deepcopy 메소드를 사용한다.

In [74]:
print (a is b)  #메모리 주소
print (a == b)  # 값 주소

False
True


In [75]:
b[0][0] = 10

In [76]:
print(a[0])
print(b[0])

[1, 2, 3]
[10, 2, 3]


In [77]:
print(a[0] == b[0])
print(a[0] is b[0])

False
False


[:] 는 전체라는 뜻이다.   
슬라이싱 방식으로 1차 리스트 일때는 재할당 하면 deep copy가 발생된다.   
슬라이싱 방식으로 2차 리스트 이상인 경우는 shallow copy가 발생된다.  

In [78]:
a = [1,2,3]
b= a[:]

print (a is b)
print (a == b )

a = [[1,2,3]]
b = a[:]
print (a is b)
print (a == b)

False
True
False
True


In [79]:
m= 100
n= m
print (m is n )
print (m == n )

True
True


In [81]:
a = 256
b = 256

a is b   # True

a = 257
b = 257

a is b    #False

False

In [96]:
 a = [257,2,3]
 b = a[:]

 print( a == b )
 print(a is b )


print(id(a))
print(id(b))
print(a[0] == b[0])
print(a[0] is b[0])

True
False
138346780574784
138346780586944
True
True


In [95]:
# intering 기법
# 파이썬은 느리기 때문에 중간에 cache 저장하는 기법이 있다.
# -5에서 256은 파이썬에서 같은 메모리 주소를 사용한다. (interning 기법)
# 문자열에서 a-zA-Z0-9는 내부적으로 interning 기법을 사용한다. (한글은 무조건 다른메모리를 사용함.)
# is 는 값을 비교

m= 256
n = 256
print (m is n )      ## -5 ~ 256 까지는 같은 메모리를 쓰기때문에 같다

m=257
n=257
print(m is n )       ## 257 이기 때문에 각각 다른 메모리를 써서 False

k = 'python3_파이썬'
p = 'python3_파이썬'  # 한글은 다른 메모리를 사용함 False 한글빼면 True

print(k is p)

True
False
False
