<a href="https://colab.research.google.com/github/onleey/numpy_demo/blob/master/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%ED%8C%90%EB%8B%A4%EC%8A%A4_300%EC%A0%9C_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


https://wikidocs.net/125545



In [2]:
import numpy as np

In [ ]:
data = [1, 2, 3]


np.array(data)


array([1, 2, 3])

In [ ]:
np.array(range(0,100))

np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr = np.arange(1,10)*3
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.arange(2,1000,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

In [ ]:
arr = np.arange(0,1,0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
data = [0, 1, 2, 3, 4, 5]

arr = np.array(data)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

#arr.reshape(1,6)
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [4]:

arr= np.arange(3)
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

In [9]:
a = [[0,1,2],[3,4,5]]
np.array(a)

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
data=[1]*20
np.array(data)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.ones(20,dtype=int).reshape(4,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
arr= np.ones(100, dtype=int).reshape(10,10)
arr = arr * 255
arr

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [27]:
np.zeros(12,dtype=int).reshape(3,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
data=[1,2,3]
np.array(data, dtype=float)

array([1., 2., 3.])

In [34]:
data = [1, 2, 3]
arr = np.ndarray(data, dtype=np.int32)
arr

array([[[         0, 1072693248,          0],
        [1073741824,          0, 1074266112]]], dtype=int32)

In [37]:
arr = np.array([1, 2, 3])
print(arr.dtype)

int64


In [38]:
arr = np.array(['1', '2', '3'])
print(arr.dtype)

<U1


In [39]:
arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [44]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
arr.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [45]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [67]:
arr = np.arange(9).reshape(3, 3)

print(arr[2])

[6 7 8]


In [73]:
arr = np.arange(9).reshape(3, 3)

print(arr[:,2])

[2 5 8]


In [74]:
arr = np.arange(25).reshape(5, 5)
print(arr[3,2])

17


In [84]:
arr = np.arange(5)
print(arr[1::2])
print(arr[[1,3]])

[1 3]
[1 3]


In [87]:
arr = np.arange(25).reshape(5, 5)
print(arr[1][1:])

[6 7 8 9]


In [97]:
arr = np.arange(25).reshape(5, 5)
print(arr[0],arr[1])
print(arr[:,:2])

[0 1 2 3 4] [5 6 7 8 9]
[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]


In [114]:
arr = np.arange(25).reshape(5, 5)
print(arr[1:3,1:3])

[[ 6  7]
 [11 12]]


In [151]:
arr = np.arange(25).reshape(5, 5)
arr
print(arr[[0,-1],[0,3]])

[ 0 23]


In [152]:
data = [1, 2, 3]
np.array(data)*10

array([10, 20, 30])

In [159]:
data = [1, 2, 3]
np.array(data)**2

array([1, 4, 9])

In [164]:
data = [1, 2, 3]
print(np.sqrt(data))
np.array(data)**0.5

[1.         1.41421356 1.73205081]


array([1.        , 1.41421356, 1.73205081])

In [179]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
print(score.mean(axis=0))

[12. 18.]


In [184]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
print(score.std(axis=1))

[5. 1.]


In [185]:
a = np.arange(4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
print(a@b)

[[ 3  4]
 [11 16]]


In [190]:
arr = np.arange(9).reshape(3, 3)
arr
print(arr.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [214]:
arr = np.arange(10)

print(arr[arr %2 ==0])

[0 2 4 6 8]


In [215]:
arr = np.arange(10)
print(arr[arr %2 ==1])

[1 3 5 7 9]


In [219]:
arr = np.array([-1, 2, -3, 4])
print(arr[arr<0])


[-1 -3]


In [232]:
arr = np.array([-1, 2, -3, 4])
cond = arr < 0
print(arr[cond]== -arr[cond])

[False False]


In [235]:
arr = np.array([-1, 2, -3, 4])
print(arr[arr>0]+10)
print(arr[arr<0]-10)

[12 14]
[-11 -13]


In [237]:
arr = np.array([-1, 2, -3, 4])
negative_cond = arr < 0
psotive_cond = arr >= 0
arr[negative_cond] = arr[negative_cond] - 10
arr[psotive_cond] = arr[psotive_cond] + 10
print(arr)

[-11  12 -13  14]


In [248]:
arr = [1, 2, 3, 4, 5]
print(arr[shuffle(arr)])

NameError: ignored

In [262]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

np.argmin(arr)

0

In [263]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.argmax(arr)

7

In [265]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [283]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3= [arr1,arr2]


arr4= np.vstack([arr3])
arr4

array([[1, 2],
       [3, 4]])

In [289]:
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])